/**
 * @file toy.h
 * @brief Enhanced WiFi Network Simulation Data Structures
 * 
 * This file defines the shared data structures used for communication between
 * NS3 C++ WiFi simulation and Python AI/ML analysis processes via shared memory.
 * 
 * This WiFi simulation captures:
 * - Station (STA) position and mobility
 * - Network throughput metrics (uplink/downlink)
 * - Access Point (AP) transmission parameters
 * - Real-time network performance data
 */

#ifndef TOY_H
#define TOY_H

#include <cstdint>

/**
 * @struct EnvStruct
 * @brief Environment data structure (C++ → Python direction)
 * 
 * Contains real-time WiFi network data generated by the NS3 simulation
 * that needs to be processed by Python for analysis and visualization.
 * This structure is written by C++ and read by Python.
 */
struct EnvStruct
{
    double env_pos_x;      ///< STA X position in meters (network topology coordinate)
    double env_pos_y;      ///< STA Y position in meters (network topology coordinate)
    double env_distance;   ///< Distance from STA to AP in meters
    double env_dl_tp;      ///< Downlink throughput in Mbps (AP → STA)
    double env_ul_tp;      ///< Uplink throughput in Mbps (STA → AP)
    double env_get_ApTx;   ///< Current AP transmission power or MCS index
    int    env_sta_id;     ///< Station ID (0-based indexing for multi-STA networks)
    double env_now_sec;    ///< Current simulation time in seconds
};

/**
 * @struct ActStruct  
 * @brief Action data structure (Python → C++ direction)
 * 
 * Contains control commands computed by Python AI/ML algorithms
 * that need to be applied to the NS3 WiFi simulation. This structure
 * is written by Python and read by C++.
 */
struct ActStruct
{
    double env_set_ApTx;   ///< New AP transmission power/MCS to set (Python → C++)
                          ///< Can be used for adaptive transmission control,
                          ///< power management, or MCS selection algorithms
};

#endif // TOY_H