/*
 * Copyright (c) 2025 Texas State University
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: Ahmed Maksud <ahmed.maksud@email.ucr.edu>
 * PI: Marcelo Menezes De Carvalho <mmcarvalho@txstate.edu>
 * Texas State University
 */

/**
 * @file wifi_data_structures.h
 * @brief WiFi Network Simulation Data Structures for NS3-AI Communication
 *
 * This file defines the shared data structures used for communication between
 * NS3 C++ WiFi simulation and Python AI/ML analysis processes via shared memory.
 *
 * This WiFi simulation captures:
 * - Station (STA) position and mobility
 * - Network throughput metrics (uplink/downlink)
 * - Access Point (AP) transmission parameters
 * - Real-time network performance data
 */

#ifndef WIFI_DATA_STRUCTURES_H
#define WIFI_DATA_STRUCTURES_H

#include <cstdint>

/**
 * @struct EnvStruct
 * @brief Environment data structure (C++ → Python direction)
 *
 * Contains real-time WiFi network data generated by the NS3 simulation
 * that needs to be processed by Python for analysis and visualization.
 * This structure is written by C++ and read by Python.
 */
struct EnvStruct
{
    double env_pos_x;    ///< STA X position in meters (network topology coordinate)
    double env_pos_y;    ///< STA Y position in meters (network topology coordinate)
    double env_distance; ///< Distance from STA to AP in meters
    double env_dl_tp;    ///< Downlink throughput in Mbps (AP → STA)
    double env_ul_tp;    ///< Uplink throughput in Mbps (STA → AP)
    double env_get_ApTx; ///< Current AP transmission power or MCS index
    int env_sta_id;      ///< Station ID (0-based indexing for multi-STA networks)
    double env_now_sec;  ///< Current simulation time in seconds
};

/**
 * @struct ActStruct
 * @brief Action data structure (Python → C++ direction)
 *
 * Contains control commands computed by Python AI/ML algorithms
 * that need to be applied to the NS3 WiFi simulation. This structure
 * is written by Python and read by C++.
 */
struct ActStruct
{
    double env_set_ApTx; ///< New AP transmission power/MCS to set (Python → C++)
                         ///< Can be used for adaptive transmission control,
                         ///< power management, or MCS selection algorithms
};

#endif // WIFI_DATA_STRUCTURES_H